### ISSUE TITLE
Potential secret spillage?

### ISSUE THREAD

**Issue by jackharrhy** [Chococoin/CrystalChocolate#1]
https://raw.githubusercontent.com/Chococoin/CrystalChocolate/master/config/key.js

^ seems to contain some secrets you might _not_ want to be in the repository.

:chocolate_bar: :chocolate_bar: :chocolate_bar:

**Comment by Chococoin** [comment]
Hi Jackharry,

We are in an early development state. Security is a big issue, I know but at the moment our concern is to demonstrate how the dapp runs to interested people, with little individual setup. In production, we'll use vault to secure all that leaks.

Thank your feedback.

**Comment by Chococoin** [comment]
Hi Jackharry,

We are in an early development state. Security is a big issue, I know, but at the moment our concern is to demonstrate how the dapp runs to interested people, with little individual setup. For production, we'll use "vault"* to secure all that leaks of sensitive data.

It could be a great opportunity to offer a bounty and start accepting pulls request.
Are you interested to work with it? 

I may create a smart contract for a bounty of 1 ETH.

In any case, thank you for your feedback. 

* https://www.vaultproject.io/docs/vs/kms.html

**Comment by jackharrhy** [comment]
silly choc
